spring:
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false

  datasource:
    url: jdbc:mysql://118.89.182.118:3306/rms?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: game
    password: 123
    driver-class-username: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true

#server:
#  tomcat:
#    uri-encoding: UTF-8

alipay:
  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  app_id:
  # 商户私钥，您的PKCS8格式RSA2私钥
  merchant_private_key:
  # 支付宝公钥，查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥
  alipay_public_key:
  # 服务器异步通知页面路径，需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notify_url:
  # 页面跳转同步通知页面路径，需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  return_url:
  # 签名方式
  sign_type: RSA2
  # 字符编码格式
  charset: utf-8
  # 支付宝网关
  gateway_url: https://openapi.alipay.com/gateway.do
  # 日志路径
  log_path:

wxpay:
    appId: wxa5f7a37b2d85c419
    APPSecret: f8e4c5603b328bffc729f84a305ff89b
    mchId: 1501344151
    mchKey: C8LaZ3Fq4h3CK8LW2gxPdto7NQ6yTfXD
    notifyUrl:

mms:
  store_home: .